# Generated by Django 3.1.7 on 2022-07-19 04:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_course_participants'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='rating',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='coursesource',
            name='image',
            field=models.ImageField(default='default-course.png', upload_to='CourseSources-Images/'),
        ),
    ]
