# Generated by Django 3.1.7 on 2022-07-19 06:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0003_auto_20220719_0437'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='image',
        ),
        migrations.AddField(
            model_name='course',
            name='image_url',
            field=models.URLField(default='https://google.com'),
            preserve_default=False,
        ),
    ]
