# Generated by Django 3.1.7 on 2022-07-28 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0004_auto_20220719_0600'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='teacher',
            field=models.CharField(default='Teacher', max_length=50),
        ),
    ]
