# Generated by Django 4.1 on 2022-08-29 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0006_course_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='description',
            field=models.TextField(default='No Information'),
        ),
        migrations.AlterField(
            model_name='course',
            name='image_url',
            field=models.URLField(default='https://learning.unv.org/theme/image.php/mb2aofk/theme/1647859262/course-default'),
        ),
        migrations.AlterField(
            model_name='course',
            name='participants',
            field=models.IntegerField(default=-1),
        ),
        migrations.AlterField(
            model_name='course',
            name='price',
            field=models.IntegerField(default=-1),
        ),
        migrations.AlterField(
            model_name='course',
            name='rating',
            field=models.FloatField(default=-1),
        ),
    ]
